[tool.poetry]
name = "ast"
version = "0.0.1"
description = ""
authors = ["John Walz <johnwalz97@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
